name: Main Workflow
on: [push]
jobs:
  greet_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Call composite Action
      uses: ./.github/actions
      with:
        who-to-greet: "Developer"